### PR TITLE
Autocomplete: Aggregated search engine (multi-source)

### PR DESCRIPTION
**Pull request by nfsmaniac**
A new function that is able to search from multiple sources at the same time was added.
In this pull request, only Slash command's AutoComplete feature is connected to the introduced aggregated search engine.
After further testing, it can be used also in `!search` command in the future.
In `config.js` file, exact list and order of Search Providers can be specified.

The biggest trouble is with SoundCloud, as its song's URIs can easily exceed 100 of characters, which is maximum for interaction.autocomplete.value in the Discord's REST API. However, some workarounds to avoid it were done.
Anyway, current limitation is, that no song exceeding maximal URL length cannot be shown in AutoComplete. Maybe we will have to use some other identifier to act as Autocomplete's value. E.g. generate custom identifiers, hold them in memory as well as their related full URL, then use it.

image

### CODE REVIEW

**Review by Legoman99573 — COMMENTED** [review]
I do like this PR. Is it possible to integrate into the /search command as well? It can be a separate PR if needed.

**Comment by NotAditya69** [comment]
you can use the sound cloud uri identifiers and later on use those identifiers to make up a full uri i haven't worked much with soundcloud metadata yet but if this approach works please integrate it in the pull request if it doesn't tell me and i'll merge it anyways

**Comment by NotAditya69** [comment]
> I do like this PR. Is it possible to integrate into the /search command as well? It can be a separate PR if needed.

this is a feature request open a issue and add the tag enhancement.

**Comment by nfsmaniac** [comment]
> you can use the sound cloud uri identifiers and later on use those identifiers to make up a full uri

Thank you for your suggestion.
I will have to investigate, how and whether I can obtain the shorter SoundCloud URI from Lavalink. Erela.js seems to be getting and returning the long URI only. At worst, we will have to implement a dedicated solution, register own SoundCloud API key, and using their API resolve the long string URI to short URI with numeric track.id.

**Comment by nfsmaniac** [comment]
There is the track_id returned in Track.identifier, although it's not clean and is part of some long link to HLS stream.
However, direct SoundCloud API access would be needed to resolve it back to URL.
Also, with API key, we'll be able to introduce Autoplay feature for SoundCloud.

**Comment by NotAditya69** [comment]
> There is the track_id returned in Track.identifier, although it's not clean and is part of some long link to HLS stream. However, direct SoundCloud API access would be needed to resolve it back to URL. Also, with API key, we'll be able to introduce Autoplay feature for SoundCloud.

Hmm alright I see, ig I'll merge this for now and once am done with the api credentials and metadata exchange I'll create the pr for it

**Pull request merged**
