### PR TITLE
fix: efficint data handling, delete data from database if there's no guild or it's entities

### PR DESCRIPTION
**Pull request by NotAditya69**
Don't merge it until unless @PandaIN95 @RedolentHalo gives there suggestions or reviews on it if it's ok merge it you too please check it

### CODE REVIEW

**Comment by NotAditya69** [comment]
@LucasB25 pushed the fix i am fetching instead of cache now since not all guilds are cached that's why you were facing that issue

**Comment by LucasB25** [comment]
for the moment I do not accept in case your a fix to do

**Comment by NotAditya69** [comment]
> for the moment I do not accept in case your a fix to do

yea wait for pandal for his reviews on the database commit

**Comment by LucasB25** [comment]
`(node:21813) [MONGODB DRIVER] Warning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.`

Take a mongo db error from your addition

**Comment by NotAditya69** [comment]
@LucasB25 you can merge it ig if pandal has anything to say he can say after it's merged

**Comment by LucasB25** [comment]
```
TypeError: Cannot read properties of undefined (reading 'send')
    at Lavamusic._sendPayload (/home/XXX/lavamusic/src/structures/Lavamusic.js:309:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.send (/home/XXX/lavamusic/src/structures/Lavamusic.js:274:36) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Lavamusic._sendPayload (/home/XXX/lavamusic/src/structures/Lavamusic.js:309:35)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.send (/home/XXX/lavamusic/src/structures/Lavamusic.js:274:36)
}

always present
```

**Comment by NotAditya69** [comment]
> ```
> TypeError: Cannot read properties of undefined (reading 'send')
>     at Lavamusic._sendPayload (/home/XXX/lavamusic/src/structures/Lavamusic.js:309:35)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.send (/home/XXX/lavamusic/src/structures/Lavamusic.js:274:36) Promise {
>   <rejected> TypeError: Cannot read properties of undefined (reading 'send')
>       at Lavamusic._sendPayload (/home/XXX/lavamusic/src/structures/Lavamusic.js:309:35)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)
>       at async Object.send (/home/XXX/lavamusic/src/structures/Lavamusic.js:274:36)
> }
> 
> always present
> ```

bro what wtf that's not possible come support channel it seems i'll have to investigate your issue more better

**Pull request merged**
