### PR TITLE
Hatry4 adding command

### PR DESCRIPTION
**Pull request by hatry4**
Easy reload your command!

### CODE REVIEW

**Comment by LucasB25** [comment]
Thank you for the proposal but it will be necessary to do it also in slash commands

**Comment by hatry4** [comment]
> Thank you for the proposal but it will be necessary to do it also in slash commands
But it's for the owner command? I didn't add in slash because eval is not in slash too

**Comment by LucasB25** [comment]
it should also be added and eval will be put in slash commands also after

**Comment by hatry4** [comment]
Uhm hey I can't add reload command in slash because all slash commands don't have a category string 

Example:
"category": "Music"
https://cdn.discordapp.com/attachments/968577976683864154/1009049399667732510/unknown.png

**Pull request merged**
