### PR TITLE
fix: Minor bugs

### LINKED ISSUE #225: lists errors found [Update EU: 22/07 EN: 07/22]
```
TypeError: Cannot read properties of undefined (reading 'title')
    at Object.execute (/home/XXX/lavamusic/src/commands/Music/remove.js:43:52)
    at Object.run (/home/XXX/lavamusic/src/events/Client/messageCreate.js:122:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### PR DESCRIPTION
**Pull request by Anonymous4078**
This PR makes the following changes:
- [x] Removes all  redundant Intents from the Client constructor
- [x] Closes #225

### CODE REVIEW

**Comment by LucasB25** [comment]
https://github.com/brblacky/lavamusic/issues/225
If you want to have fun there are those mistakes too (:

**Comment by brblacky** [comment]
Guildinvite need for guild create invite system

**Review by LucasB25 — COMMENTED** [review]
add  GatewayIntentBits.GuildInvites,

**Review by LucasB25 — COMMENTED** [review]
There are errors corrected here

**Comment by LucasB25** [comment]
Do you have any ideas about that?

**During a Lavalain crash or connection the beautiful remains as in the vocal while physically it no longer has it then it is necessary to disconnect it manually**

**Pull request merged**
