### PR TITLE
Fixed Slash command play.js & queue.js

### PR DESCRIPTION
**Pull request by AikoNee**
play.js = won't restart player when adding playlist in slash command anymore.
also changed `interaction.user` to `interaction.member.user` cause why not?

queue.js = remove track.uri component for Spotify song titles to show up

### CODE REVIEW

**Comment by LucasB25** [comment]
If these concerns also exist in the message commands thank you to fix them with history of solved the problem completely.
If not, we thank you

**Review by brblacky — CHANGES_REQUESTED** [review]
pretty-ms i think don't need, convertTime also be work

**Comment by AikoNee** [comment]
Aight

**Comment by AikoNee** [comment]
> If these concerns also exist in the message commands thank you to fix them with history of solved the problem completely. If not, we thank you

I think the message is fine

**Pull request merged**
