### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ZenoX-Twitch**
Change package.json !

### CODE REVIEW

**Comment by NotAditya69** [comment]
changing versions will break things and downgrade is just not acceptable.

**Comment by ZenoX-Twitch** [comment]
I had some problems with the `dotenv` module which does not work in version `16.0.3` but works in version `14.3.2`

**Comment by ZenoX-Twitch** [comment]
image

**Comment by RafCodez** [comment]
We had this error

**Comment by RafCodez** [comment]
This error probably causing for you. Because you are the 1st one to talk about this.

**Comment by NotAditya69** [comment]
> image

That's not a related problem it occured because you provided a string and not a number

**Comment by Legoman99573** [comment]
Check .env. Keep the ""s in there as if you remove them, then this behavior occurs.

**Pull request closed without merging**
