### PR TITLE
Updated JSDoc for MusicBot#slashCommands

### PR DESCRIPTION
**Pull request by NotAditya69**
Added autocompletion for the ChatInputCommand play, Whenever the user types in a song name or link into it the interaction would respond with the matched keywords songs a example is shared below
image

### CODE REVIEW

**Comment by LucasB25** [comment]
Are they bug fixes?

**Comment by NotAditya69** [comment]
Yea

**Comment by LucasB25** [comment]
which permits carry them over?
https://github.com/brblacky/lavamusic/issues/247
https://github.com/brblacky/lavamusic/issues/247

**Comment by NotAditya69** [comment]
The bugs for the spotify url is fixed in it however autocompletion only searches with youtube data only for spotify metadata we would need to initialize the spotify api, Autocompletes makes it more safe because it directly suggests metadata from results and not unmatched content

**Comment by LucasB25** [comment]
> The bugs for the spotify url is fixed in it however autocompletion only searches with youtube data only for spotify metadata we would need to set choice[].value to be it's indentifier we can tell me if i need to add, Autocompletes makes it more safe because it directly suggests metadata from results and not unmatched content

the most appropriate option of preference

**Comment by NotAditya69** [comment]
what? didn't understand.

**Comment by LucasB25** [comment]
choose the most suitable method

**Comment by NotAditya69** [comment]
alright

**Comment by NotAditya69** [comment]
image

Ok so i have successfully made the commit you can now merge it

**Comment by LucasB25** [comment]
> which permits carry them over? #247 #247

give me the mistakes you may have corrected so that I remove them or close the exits

**Comment by LucasB25** [comment]
I was wrong I put twice the same
so it’s #224 & 225

**Comment by NotAditya69** [comment]
hmm yea conclusion is that the metadata issues are fixed

**Comment by LucasB25** [comment]
So no worries about #225 solved?
if everything and good I will do a check and I will come back to report a problem if there is one otherwise I will accept the request

**Comment by NotAditya69** [comment]
#225 remove should be fixed and other issues aren't related to my commit, After i get this merged i'll work on those and fix that wall of bugs

**Comment by LucasB25** [comment]
> #225 remove should be fixed and other issues aren't related to my commit, After i get this merged i'll work on those and fix that wall of bugs

If you have resolved any concerns in #225 please tell me which ones so I can remove them from the list

**Comment by NotAditya69** [comment]
`RangeError: Provided argument must be present.
    at Function.validate (/home/XXX/lavamusic/node_modules/erela.js/dist/structures/Utils.js:46:19)
    at Queue.add (/home/XXX/lavamusic/node_modules/erela.js/dist/structures/Queue.js:38:33)
    at module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackEnd.js:10:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
    
   `RangeError: Provided argument must be present.
    at Function.validate (/home/XXX/lavamusic/node_modules/erela.js/dist/structures/Utils.js:46:19)
    at Queue.add (/home/XXX/lavamusic/node_modules/erela.js/dist/structures/Queue.js:38:33)
    at module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackEnd.js:10:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
    
    
    This one's should be fixed

**Comment by LucasB25** [comment]
ok thx

**Comment by NotAditya69** [comment]
Are you going to merge it?

**Pull request merged**
