### PR TITLE
breaking change: node js requirement level raised to version 18

### PR DESCRIPTION
**Pull request by NotAditya69**
Removed useless/unnecessary packages and replaced them with pre existing one's also its a breaking change the user's node js must be above version 18 due to superfetch using inbuilt node-fetch

### CODE REVIEW

**Comment by NotAditya69** [comment]
also #225 is fixed

**Comment by LucasB25** [comment]
error:
```
ReferenceError: SearchPlatform is not defined
    at new Lavamusic (/home/pi/lavamusic/src/structures/Lavamusic.js:298:30)
    at new MusicBot (/home/pi/lavamusic/src/structures/Client.js:66:20)
    at Object.<anonymous> (/home/pi/lavamusic/src/index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by LucasB25** [comment]
```
ReferenceError: fetch is not defined
    at Request._request (/home/pi/lavamusic/node_modules/node-superfetch/index.js:21:20)
    at Request.then (/home/pi/lavamusic/node_modules/node-superfetch/index.js:66:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by NotAditya69** [comment]
> lyrics command
> 
> ```
> ReferenceError: fetch is not defined
>     at Request._request (/home/pi/lavamusic/node_modules/node-superfetch/index.js:21:20)
>     at Request.then (/home/pi/lavamusic/node_modules/node-superfetch/index.js:66:15)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

read the comment it's a breaking change so you'll have to update your node js version

**Comment by NotAditya69** [comment]
> error:
> 
> ```
> ReferenceError: SearchPlatform is not defined
>     at new Lavamusic (/home/pi/lavamusic/src/structures/Lavamusic.js:298:30)
>     at new MusicBot (/home/pi/lavamusic/src/structures/Client.js:66:20)
>     at Object.<anonymous> (/home/pi/lavamusic/src/index.js:2:16)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:17:47
> ```

issue from your side check your config.js

**Comment by LucasB25** [comment]
> issue from your side check your config.js

you put "SearchPlatform" without uppercase while config and with

**Comment by Legoman99573** [comment]
It is suppose to be SearchPlatform. Lowercase will just break it without config.js and .env changes.

**Comment by NotAditya69** [comment]
> It is suppose to be SearchPlatform. Lowercase will just break it without config.js and .env changes.

It is already fixed just have a look

**Comment by NotAditya69** [comment]
Secondly your env file has searchPlatform and not SearchPlatform and i don't see any way of it breaking the environment variables anyways

**Comment by Legoman99573** [comment]
I just noticed. The S was suppose to be capatalized originally, but yeah, it might as well be fixed.

**Pull request merged**
