### PR TITLE
chore: added some checks on creating 247 player and on destroy reconnect

### PR DESCRIPTION
**Pull request by NotAditya69**
on the info of @PandaIN95, Added validations and on player#destroy reconnect if 247 is enabled

### CODE REVIEW

**Comment by LucasB25** [comment]
```
SyntaxError: Unexpected end of input
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/panaisv14/src/events/Lavalink/nodeConnect.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
/home/pi/panaisv14/src/utils/functions.js:396
```

**Comment by LucasB25** [comment]
TypeError: Cannot read properties of undefined (reading 'send')
    at Lavamusic._sendPayload (/home/pi/panaisv14/src/structures/Lavamusic.js:309:35)
    at Object.send (/home/pi/panaisv14/src/structures/Lavamusic.js:274:35)
    at Object.connect (/home/pi/panaisv14/node_modules/erela.js/dist/structures/Player.js:147:30)
    at AutoConnect (/home/pi/panaisv14/src/utils/functions.js:54:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/pi/panaisv14/src/events/Lavalink/nodeConnect.js:27:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'send')
      at Lavamusic._sendPayload (/home/pi/panaisv14/src/structures/Lavamusic.js:309:35)
      at Object.send (/home/pi/panaisv14/src/structures/Lavamusic.js:274:35)
      at Object.connect (/home/pi/panaisv14/node_modules/erela.js/dist/structures/Player.js:147:30)
      at AutoConnect (/home/pi/panaisv14/src/utils/functions.js:54:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async module.exports (/home/pi/panaisv14/src/events/Lavalink/nodeConnect.js:27:5)

**Comment by NotAditya69** [comment]
checkout the origin it's not from the pushed files, else it would not work for me it's in your Lavamusic file

**Comment by LucasB25** [comment]
> checkout the origin it's not from the pushed files, else it would not work for me it's in your Lavamusic file

I checked the truth, it’s from your commit

**Comment by NotAditya69** [comment]
> > checkout the origin it's not from the pushed files, else it would not work for me it's in your Lavamusic file
> 
> I checked the truth, it’s from your commit

huh which?

**Comment by LucasB25** [comment]
> huh which?

this error

**Comment by NotAditya69** [comment]
> TypeError: Cannot read properties of undefined (reading 'send') at Lavamusic._sendPayload (/home/XXX/lavamusic/src/structures/Lavamusic.js:309:35) at Object.send (/home/XXX/lavamusic/src/structures/Lavamusic.js:274:35) at Object.connect (/home/XXX/lavamusic/node_modules/erela.js/dist/structures/Player.js:147:30) at AutoConnect (/home/XXX/lavamusic/src/utils/functions.js:54:10) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/nodeConnect.js:27:5) Promise { TypeError: Cannot read properties of undefined (reading 'send') at Lavamusic._sendPayload (/home/XXX/lavamusic/src/structures/Lavamusic.js:309:35) at Object.send (/home/XXX/lavamusic/src/structures/Lavamusic.js:274:35) at Object.connect (/home/XXX/lavamusic/node_modules/erela.js/dist/structures/Player.js:147:30) at AutoConnect (/home/XXX/lavamusic/src/utils/functions.js:54:10) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/nodeConnect.js:27:5)

i am not facing it ask some other contributors to check it too cuz if i don't face i can't fix it

**Comment by NotAditya69** [comment]
send me your nodeConnect.js

**Comment by LucasB25** [comment]
This mistake and indeed happened with your commit that you made a few days ago

**Comment by LucasB25** [comment]
It’s the same one you committed

**Comment by NotAditya69** [comment]
> This mistake and indeed happened with your commit that you made a few days ago

send me your nodeConnect.js i wanna see smtj

**Comment by LucasB25** [comment]
```
const Model = require("../../schema/247.js");
const { AutoConnect } = require("../../utils/functions.js");
const MusicBot = require("../../structures/Client.js");

/**
 *
 * @param {MusicBot} client
 * @param {Node} node
 * @returns {Promise<void>}
 */
module.exports = async (client, node) => {
  client.logger.log(`Node "${node.options.identifier}" connected.`, "ready");

  // 247 Connection
  const data = await Model.find({ 247: true });

  if (!data) return;

  const ModifyArray = data.map((value) => ({
    guild: value.Guild,
    voicechannel: value.VoiceChannel,
    textchannel: value.TextChannel,
    status: value[247],
  }));

    for (const obj of ModifyArray) {
    await AutoConnect(obj, client);
  }
};
```

**Comment by NotAditya69** [comment]
> ```
> const Model = require("../../schema/247.js");
> const { AutoConnect } = require("../../utils/functions.js");
> const MusicBot = require("../../structures/Client.js");
> 
> /**
>  *
>  * @param {MusicBot} client
>  * @param {Node} node
>  * @returns {Promise<void>}
>  */
> module.exports = async (client, node) => {
>   client.logger.log(`Node "${node.options.identifier}" connected.`, "ready");
> 
>   // 247 Connection
>   const data = await Model.find({ 247: true });
> 
>   if (!data) return;
> 
>   const ModifyArray = data.map((value) => ({
>     guild: value.Guild,
>     voicechannel: value.VoiceChannel,
>     textchannel: value.TextChannel,
>     status: value[247],
>   }));
> 
>     for (const obj of ModifyArray) {
>     await AutoConnect(obj, client);
>   }
> };
> ```

ok so does your Lavamusic.js has a private method _sendPayload if so send me that it seems that's undefined in your case

**Comment by LucasB25** [comment]
it’s the same as this repo

**Comment by NotAditya69** [comment]
> it’s the same as this repo

it's a cache problem the guild you are sending it for isn't cached i am gonna push this fix in the current pr i opened mins ago

**Comment by LucasB25** [comment]
ok

**Pull request merged**
