### PR TITLE
Fixed an error where it doesn't play songs on latest version of nodejs.

### PR DESCRIPTION
**Pull request by RafCodez**
Fixed an error where bot doesn't play song and shows error (there was an error while searching: Unexpected token  in JSON at position 0) by installing erela.js build version.

### CODE REVIEW

**Comment by LucasB25** [comment]
why build branche ?

**Comment by Gremagol** [comment]
This one fixes the Unexpected Token in JSON error, that's why. Also erela.js doesn't update in node packages, you have to pull from GitHub in order to receive it's latest updates.

**Comment by RafCodez** [comment]
Erela.js was transferred to MenuDocs, because owner no longer wish to work with Discord related development. It is now maintained by MenuDocs. 

Build branch(MenuDocs/erela.js#build) is latest version thats why and it was suggested by erela.js support server.

**Comment by LucasB25** [comment]
```
TypeError: Cannot read properties of null (reading 'Channel')
    at module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:40:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'Channel')
      at module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:40:20)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}

```

I’ll let you fix this mistake before

**Pull request merged**
