### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by NotAditya69**
**Description**
Fixed many bugs in the main branch i'll list them here

- Fixed the now playing thumbnails for soundcloud
- Fixed uri not showing up for other platforms like spotify and soundcloud
- Fixed the error data.Channel being null
- Fixed autocompletion bug input as the value

### CODE REVIEW

**Comment by LucasB25** [comment]
bug fix ? https://github.com/brblacky/lavamusic/issues/273
bug fix ? https://github.com/brblacky/lavamusic/issues/276
Errors have been corrected here? if so what? https://github.com/brblacky/lavamusic/issues/225

**Comment by NotAditya69** [comment]
This fix doesn't contains #225 issues that would be fixed on the next pr this issue fixed #273 and also #276 and some more issues which weren't reported till now and i have seen people asking help in the support server so there's a lot of bug fixes this also includes this one you were asking about today in the support channel

```js
TypeError: Cannot read properties of null (reading 'Channel')
    at module.exports (/home/pi/panaisv14/src/events/Lavalink/trackStart.js:38:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'Channel')
      at module.exports (/home/pi/panaisv14/src/events/Lavalink/trackStart.js:38:22)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}
```

**Comment by LucasB25** [comment]
I check all check be correct is there anything else added in the query where I can now accept it?

**Comment by NotAditya69** [comment]
Accept it

**Comment by LucasB25** [comment]
I just saw but you made some changes on slashs command but not the message commands, an oversight?

**Comment by LucasB25** [comment]
```
DiscordAPIError[50035]: Invalid Form Body
21[APPLICATION_COMMANDS_DUPLICATE_NAME]: Application command names must be unique
    at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async /home/XXX/lavamusic/src/handlers/slashCommand.js:52:7 {
  rawError: {
    code: 50035,
    errors: { '21': [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/707627135577358417/commands',
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object]
    ]
  }
}
```

**Comment by LucasB25** [comment]
you duplicated the auto play command with play

**Comment by NotAditya69** [comment]
> ```
> DiscordAPIError[50035]: Invalid Form Body
> 21[APPLICATION_COMMANDS_DUPLICATE_NAME]: Application command names must be unique
>     at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
>     at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
>     at async /home/XXX/lavamusic/src/handlers/slashCommand.js:52:7 {
>   rawError: {
>     code: 50035,
>     errors: { '21': [Object] },
>     message: 'Invalid Form Body'
>   },
>   code: 50035,
>   status: 400,
>   method: 'PUT',
>   url: 'https://discord.com/api/v10/applications/707627135577358417/commands',
>   requestBody: {
>     files: undefined,
>     json: [
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object], [Object], [Object],
>       [Object], [Object]
>     ]
>   }
> }
> ```

Is this from my commits? I didn't change the name field for the play command check my dev branch it doesn't includes similar names

**Comment by NotAditya69** [comment]
> I just saw but you made some changes on slashs command but not the message commands, an oversight?

Well only made on play command and did on both other bugs were on emitters

**Comment by LucasB25** [comment]
> Is this from my commits? I didn't change the name field for the play command check my dev branch it doesn't includes similar names

yes it comes from your clerk before setting it up I do checks and this concern did not exist before the addition of your clerk

**Comment by NotAditya69** [comment]
But i don't find any conflicts in my part of the branch that has similar names?

**Comment by NotAditya69** [comment]
Can you try recloning my fork (dev branch) and try again

**Comment by LucasB25** [comment]
it’s me I didn’t say anything

on the other hand there is really a mistake
`Oops! Error: 503 Service Unavailable`

**Comment by NotAditya69** [comment]
So that issue was from your side right?

**Comment by NotAditya69** [comment]
Also 503? I want see a full screenshot

**Comment by LucasB25** [comment]
> So that issue was from your side right?

yes

**Comment by LucasB25** [comment]
> Also 503? I want see a full screenshot

there is nothing but that

**Comment by NotAditya69** [comment]
Check your config.js if it has the Spotify and other credentials

**Comment by LucasB25** [comment]
> Check your config.js if it has the Spotify and other credentials

yes there is and it’s okay

**Comment by NotAditya69** [comment]
So this 503 error pops up on starting the bot right can you send me your terminal screenshot?

**Comment by LucasB25** [comment]
> So this 503 error pops up on starting the bot right can you send me your terminal screenshot?

image

**Comment by NotAditya69** [comment]
This error is from your Lavalink server not from my commits

**Comment by LucasB25** [comment]
there are slash commands where you left "message", when it must be "interaction"

**Comment by NotAditya69** [comment]
> there are slash commands where you left "message", when it must be "interaction"

Tell me the file names

**Comment by LucasB25** [comment]
> > there are slash commands where you left "message", when it must be "interaction"
> 
> Tell me the file names

Play: then there must be others

**Comment by LucasB25** [comment]
```
Error: InteractionAlreadyReplied
    at AutocompleteInteraction.respond (/home/XXX/lavamusic/node_modules/discord.js/src/structures/AutocompleteInteraction.js:84:31)
    at Object.run (/home/XXX/lavamusic/src/events/Client/interactionCreate.js:65:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
Error: InteractionAlreadyReplied
    at AutocompleteInteraction.respond (/home/XXX/lavamusic/node_modules/discord.js/src/structures/AutocompleteInteraction.js:84:31)
    at Object.run (/home/XXX/lavamusic/src/events/Client/interactionCreate.js:65:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException

```
error from your commit

**Comment by NotAditya69** [comment]
> > > there are slash commands where you left "message", when it must be "interaction"
> > 
> > 
> > Tell me the file names
> 
> Play

I'll fix it

**Comment by NotAditya69** [comment]
> ```
> Error: InteractionAlreadyReplied
>     at AutocompleteInteraction.respond (/home/XXX/lavamusic/node_modules/discord.js/src/structures/AutocompleteInteraction.js:84:31)
>     at Object.run (/home/XXX/lavamusic/src/events/Client/interactionCreate.js:65:33)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
> Error: InteractionAlreadyReplied
>     at AutocompleteInteraction.respond (/home/XXX/lavamusic/node_modules/discord.js/src/structures/AutocompleteInteraction.js:84:31)
>     at Object.run (/home/XXX/lavamusic/src/events/Client/interactionCreate.js:65:33)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
> ```
> 
> error from your commit

I didn't update auto complete

**Comment by LucasB25** [comment]
> * autocompletion

you have a fix autocompletion bug as much fix this one with

**Comment by NotAditya69** [comment]
i have fixed them

**Comment by NotAditya69** [comment]
Once the merge is done after you have done the checks then close these issues i mentioned below

- #281
- #276
- #273

**Comment by LucasB25** [comment]
I do a small check to see if there are any returns of error and if this is not the case I accept it

**Comment by LucasB25** [comment]
```
DiscordAPIError[10008]: Unknown Message
    at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
    at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
    at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
    at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
  rawError: { message: 'Unknown Message', code: 10008 },
  code: 10008,
  status: 404,
  method: 'DELETE',
  url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
  requestBody: { files: undefined, json: undefined }
} Promise {
  <rejected> DiscordAPIError[10008]: Unknown Message
      at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
      at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
      at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
      at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
      at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
      at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
    rawError: { message: 'Unknown Message', code: 10008 },
    code: 10008,
    status: 404,
    method: 'DELETE',
    url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
    requestBody: { files: undefined, json: undefined }
  }
}
```

**Comment by NotAditya69** [comment]
> ```
> DiscordAPIError[10008]: Unknown Message
>     at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
>     at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
>     at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
>     at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
>     at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
>     at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
>   rawError: { message: 'Unknown Message', code: 10008 },
>   code: 10008,
>   status: 404,
>   method: 'DELETE',
>   url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
>   requestBody: { files: undefined, json: undefined }
> } Promise {
>   <rejected> DiscordAPIError[10008]: Unknown Message
>       at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)
>       at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
>       at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
>       at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
>       at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
>       at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
>       at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
>     rawError: { message: 'Unknown Message', code: 10008 },
>     code: 10008,
>     status: 404,
>     method: 'DELETE',
>     url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
>     requestBody: { files: undefined, json: undefined }
>   }
> }
> ```

That's a unknown message error you can safely ignore it it's always catched by the exceptions these appears whenever a message is to be edited/deleted but the message doesn't exists not a big deal that's completely random

**Comment by NotAditya69** [comment]
Are you using my fork dev branch?

**Comment by NotAditya69** [comment]
@PandaIN95 check now

**Comment by NotAditya69** [comment]
the function occurances has it i'll have to change it for all of them it seems you probably have a different setup for the bot anyways i'll do it and push again and then try

**Comment by NotAditya69** [comment]
@PandaIN95 you can retry now

**Comment by NotAditya69** [comment]
how can that still be null what? can you send me the snippet here

**Comment by NotAditya69** [comment]
https://user-images.githubusercontent.com/90441096/189527201-1d4b0a09-18f5-4c05-b1c8-775bccf4028f.mp4

Works perfectly

**Comment by LucasB25** [comment]
> > ```
> > DiscordAPIError[10008]: Unknown Message
> >     at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
> >     at runMicrotasks (<anonymous>)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
> >     at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
> >     at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
> >     at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
> >     at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
> >     at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
> >   rawError: { message: 'Unknown Message', code: 10008 },
> >   code: 10008,
> >   status: 404,
> >   method: 'DELETE',
> >   url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
> >   requestBody: { files: undefined, json: undefined }
> > } Promise {
> >   <rejected> DiscordAPIError[10008]: Unknown Message
> >       at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
> >       at runMicrotasks (<anonymous>)
> >       at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >       at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
> >       at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
> >       at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
> >       at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
> >       at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
> >       at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
> >     rawError: { message: 'Unknown Message', code: 10008 },
> >     code: 10008,
> >     status: 404,
> >     method: 'DELETE',
> >     url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
> >     requestBody: { files: undefined, json: undefined }
> >   }
> > }
> > ```
> 
> That's a unknown message error you can safely ignore it it's always catched by the exceptions these appears whenever a message is to be edited/deleted but the message doesn't exists not a big deal that's completely random

it spam a lot so it’s som importance

**Comment by NotAditya69** [comment]
> > > ```
> > > DiscordAPIError[10008]: Unknown Message
> > >     at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
> > >     at runMicrotasks (<anonymous>)
> > >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > >     at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
> > >     at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
> > >     at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
> > >     at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
> > >     at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
> > >     at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
> > >   rawError: { message: 'Unknown Message', code: 10008 },
> > >   code: 10008,
> > >   status: 404,
> > >   method: 'DELETE',
> > >   url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
> > >   requestBody: { files: undefined, json: undefined }
> > > } Promise {
> > >   <rejected> DiscordAPIError[10008]: Unknown Message
> > >       at SequentialHandler.runRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:287:15)
> > >       at runMicrotasks (<anonymous>)
> > >       at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > >       at async SequentialHandler.queueRequest (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
> > >       at async REST.request (/home/XXX/lavamusic/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
> > >       at async MessageManager.delete (/home/XXX/lavamusic/node_modules/discord.js/src/managers/MessageManager.js:245:5)
> > >       at async Message.delete (/home/XXX/lavamusic/node_modules/discord.js/src/structures/Message.js:767:5)
> > >       at async Object.setNowplayingMessage (/home/XXX/lavamusic/src/structures/Lavamusic.js:36:11)
> > >       at async module.exports (/home/XXX/lavamusic/src/events/Lavalink/trackStart.js:90:3) {
> > >     rawError: { message: 'Unknown Message', code: 10008 },
> > >     code: 10008,
> > >     status: 404,
> > >     method: 'DELETE',
> > >     url: 'https://discord.com/api/v10/channels/1018438176286724110/messages/1018470209666961408',
> > >     requestBody: { files: undefined, json: undefined }
> > >   }
> > > }
> > > ```
> > 
> > 
> > That's a unknown message error you can safely ignore it it's always catched by the exceptions these appears whenever a message is to be edited/deleted but the message doesn't exists not a big deal that's completely random
> 
> it spam a lot so it’s som importance

In next pr I'll fix them all this is also included in your #225 Since this isn't a serious issue I am gonna fix this in #225 this is totally random so this can appear on anything

**Comment by NotAditya69** [comment]
> 2022-09-11.18-33-42.mp4 
> im not any errors in console now but still the same

This seems to be a issue from your side since it works for me and Lukas too so i don't think that still stays a bug or so try to upgrade your node js and check

**Comment by NotAditya69** [comment]
@RafCodez if you don't mind can you check if the disconnect issue in #281 is fixed in my repo buy using it

**Comment by NotAditya69** [comment]
Alright I'll try it later currently am not on my pc

**Comment by RafCodez** [comment]
> @RafCodez if you don't mind can you check if the disconnect issue in #281 is fixed in my repo by using it
Issue is still present

**Comment by NotAditya69** [comment]
you guys can check now i have pushed the files once again check it, This time it should work i'll also share a video clip from my side 

https://user-images.githubusercontent.com/90441096/189595387-e6228ad4-0bd7-45bd-a4ef-353ed61c4ef3.mp4

@RafCodez @PandaIN95

**Comment by NotAditya69** [comment]
> @NotAditya69 still the same For me One Suggestion though instead of changing in play you should change the things in playerMove.js event where on bot disconnect it should destroy the player not like bot can't play the new song because of disconnect. The Right Disconnect should work like leave command that's how every bot works

how is it not working for you bruh, anyways player move will defo work but i want get new track data you see so either way i will have to reconnect again once disconnected or destroy the player else even if  it's connected on the new play execution it won't play anything since erela.js doesn't resume sessions like shoukaku

**Comment by NotAditya69** [comment]
@PandaIN95 try now also make sure you have actually pulled the updates from my fork dev branch

**Comment by NotAditya69** [comment]
> @NotAditya69 i fixed it revert all your changes you made for #281

but you only seem to destroy the player not resume the old queue? if that was the case should have told me

**Comment by NotAditya69** [comment]
@LucasB25 you can merge this now if you have any other checking to do then feel free

**Pull request merged**
