### PR TITLE
fix: 247 won't work on multiguild disconnections and not play music

### PR DESCRIPTION
**Pull request by NotAditya69**
Fixes the multiguild 247 connection

### CODE REVIEW

**Comment by NotAditya69** [comment]
> 

alright thanks for letting me, about point 1 should i also add if the voice and text channel still exists or not? it might throw some unknown channel exception if that's a case

**Comment by NotAditya69** [comment]
@RedolentHalo functions.js from line 50 or so it's defined check again

**Comment by RedolentHalo** [comment]
It ain't

**Comment by NotAditya69** [comment]
@RedolentHalo
unknown

**Comment by NotAditya69** [comment]
it is defined

**Comment by RedolentHalo** [comment]
image
and right here the data.delte the error Is occuring

**Comment by RedolentHalo** [comment]
and another bug if we make the player.destroy() it joins and leaves like 1000 times a sec

**Comment by RedolentHalo** [comment]
17 lmfao

**Comment by RedolentHalo** [comment]
it ain't because of nodejs version

**Comment by RedolentHalo** [comment]
and data.delete() is not necessary so i removed it

**Comment by RedolentHalo** [comment]
it won't play songs there cause it doesn't exist there

**Comment by RedolentHalo** [comment]
and it doesn't

**Comment by RedolentHalo** [comment]
and the data.delete() deletes the 247 servers data :)) so remember that

**Comment by RedolentHalo** [comment]
i did check and it was deleting the 247 database

**Comment by NotAditya69** [comment]
@RedolentHalo don't make unnecessary commits to break up things you should know that data.delete is there for a efficient database usage if there's no guild delete the data simple as that secondly player state is always connected whenever it is created and it's not shoukaku that would warn on connections i won't prefer using a state because whenever a bot is restarted or is disconnected/executed leave cmd the player is destroyed so therefore there is no way for the player to be connected so that check isn't required at all and that bug you are talking about is obv because you either manually deleted the data from the existing server and to solve it just use a check to see if the data isn't null if it is return not just remove the data.delete itselves

**Comment by NotAditya69** [comment]
@LucasB25 I am very disappointed rn please request reviews from everyone when merging pr's even mine too

**Comment by RedolentHalo** [comment]
check wasn't defined properly :/

**Comment by NotAditya69** [comment]
it was defined functions doesn't required to be above where their defination is even the function is below it will still be called just like classes

**Comment by RedolentHalo** [comment]
didn't work for me and better try the functions.js first and tell me if it is creating player for the guild where is it kicked from

**Comment by RedolentHalo** [comment]
and data.delete() was deleting the database information for me

**Comment by RedolentHalo** [comment]
image

**Comment by NotAditya69** [comment]
> and data.delete() was deleting the database information for me

it was because there was no data when the bot left the guild but in your commit you just removed the method you could have added a check instead if theres data or not

**Comment by NotAditya69** [comment]
> didn't work for me and better try the functions.js first and tell me if it is creating player for the guild where is it kicked from

it was never creating player for the guild from where it was kicked not in my commit onwards

**Comment by RedolentHalo** [comment]
not in mine too

**Comment by NotAditya69** [comment]
> not in mine too

then was was the problem eh

**Comment by RedolentHalo** [comment]
it was deleting the data of 247 for me and the data.delete() was useless

**Comment by NotAditya69** [comment]
how was it useless explain please

**Comment by RedolentHalo** [comment]
check it wasn't creating player for the guilds where it is kicked from when data.delete() was also not there

**Comment by NotAditya69** [comment]
> check it wasn't creating player for the guilds where it is kicked from when data.delete() was also not there

why will it create players from where it was kicked? that would just create errors

**Comment by RedolentHalo** [comment]
it didn't

**Comment by NotAditya69** [comment]
data.delete was just to clean the database and if the bot is added to the server again and they turn 247 it will work normally as it should be
still as you were facing the error null on it i have created a pr to fix it

**Comment by RedolentHalo** [comment]
image

**Comment by RedolentHalo** [comment]
he meant this

**Comment by NotAditya69** [comment]
> image

yea exactly what i did i made it not create players for them that's why the check function was introduced in the first place

**Comment by RedolentHalo** [comment]
and another thing without 
    if(player && player.state !== "CONNECTED") player.connect();
it wasn't creating any audio

**Comment by NotAditya69** [comment]
> and another thing without if(player && player.state !== "CONNECTED") player.connect(); it wasn't creating any audio

yea keep that np

**Comment by RedolentHalo** [comment]
add me in discord we are gona discuss some another bugs RedolentHalo#5880

**Pull request merged**
