### PR TITLE
Fix Args setPrefix

### PR DESCRIPTION
**Pull request by erwinowak**
This is my first change in this project, please understand because I am not an outstanding programmer. The change is that I changed pre to args without a **.join (" ")** which made it always display You can't set a prefix with a double argument!

Now the effect is as follows:
**Screenshot_1**

Unfortunately, I don't know how to do the same with slashCommand setPrefix

### CODE REVIEW

**Comment by Legoman99573** [comment]
I have pushed a PR in this fork with the slash command variant. Not much needs to be fixed really other than shrink the 3 characters to 2 characters

**Comment by erwinowak** [comment]
> I have pushed a PR in this fork with the slash command variant. Not much needs to be fixed really other than shrink the 3 characters to 2 characters

I didn't look here for two days, tried to do as you wrote, changed 3 characters to 2 and it didn't help. So the command with the prefix I pushed works fine, only the slash command has this problem.

**Comment by Legoman99573** [comment]
When I run it /via command, I have no issue with the PR. Which version of Node.js are you on?

Version I am on is nodejs v18.

**Comment by NotAditya69** [comment]
You should use prototypes rather than indexing

**Comment by erwinowak** [comment]
> When I run it /via command, I have no issue with the PR. Which version of Node.js are you on?
> 
> Version I am on is nodejs v18.

the same version

**Pull request closed without merging**
