### PR TITLE
Issue fix #302

### LINKED ISSUE #302: Auto vc after restart
### Description of your suggestion

If bot hoes offline and when it comes online it automatically connected the vc in which 247 was active. And if 247 is enabled then no one can disconnect the bot if does then bot automatically connect again untill 247 is disabled

### PR DESCRIPTION
**Pull request by NotAditya69**
Fixes not connecting on restart if 24/7 is enabled

### CODE REVIEW

**Comment by Alone-ankush** [comment]
issue kya tha

**Comment by NotAditya69** [comment]
> issue kya tha

its mentioned bruh 🗿

**Comment by Alone-ankush** [comment]
mera feature la do 🥺

**Review by RedolentHalo — COMMENTED** [review]
Hey dude seems like it doesn't send any audio after the player reconnects I guess fix it?

**Review by RedolentHalo — COMMENTED** [review]
Hmm also its really bugged with setup :D

**Comment by NotAditya69** [comment]
> @NotAditya69 if there are Multiple Guilds with 247 enabled then the Bot only Joins one single Guild.

Oh thanks for telling me the bugs i'll fix it

**Pull request merged**
